<title>Nightbird Engine | Lycia Stenson</title>

<div class="space-y-5">
	<h1 class="text-5xl font-bold">
		Nightbird Engine
	</h1>
	
	<p class="text-lg">
		Nightbird is my cross-platform C++ game engine with Vulkan rendering. Windows and Linux .
	</p>
	
	<a
		class="flex px-2 space-x-2 items-center w-fit border-2 border-black dark:border-stone-400 text-black dark:text-white rounded-lg hover:shadow-lg duration-100 hover:scale-105"
		href="https://github.com/NightbirdEngine/Nightbird"
	>
		<img src="/logos/github-icon.svg" alt="GitHub Icon" class="h-10 dark:invert"/>
		<div class="pb-1.5">
			<p class="text-lg font-bold">
				Available on
			</p>
			<img src="/logos/github-text.svg" alt="GitHub Icon" class="h-6 dark:invert"/>
		</div>
	</a>
	
	<p class="text-lg">
		Started as an OpenGL renderer to develop my understanding of graphics programming, the project became my own game engine. I migrated to Vulkan.
	</p>
	
	<img src="/nightbird/editor.png" width="600" alt="Nightbird Editor" />
	
	<div class="space-y-2">
		<h2 class="text-4xl font-bold">
			Platforms
		</h2>
		
		<div class="space-y-1">
			<p class="text-lg">
				A backend system allows platform and rendering functionality to be implemented for different platforms.
			</p>
			<div class="space-y-0">
				<p class="text-lg font-semibold">
					Tested Environments:
				</p>
				<ul class="list-disc pl-8 space-y-1 text-lg">
					<li>
						Windows 10 &amp; 11 - Visual Studio 2022
						<a href="https://premake.github.io/" target="_blank" class="italic">
							&lpar;Premake&rpar;
						</a>
					</li>
					<li>
						Linux - Make &amp; GCC
						<a href="https://premake.github.io/" target="_blank" class="italic">
							&lpar;Premake&rpar;
						</a>
					</li>
					<li>
						Nintendo Wii U - devkitPro
						<a href="https://github.com/devkitPro/wut" target="_blank" class="italic">
							&lpar;wut&rpar;
						</a>,
						<a href="https://github.com/Exzap/CafeGLSL" target="_blank" class="italic">
							&lpar;CafeGLSL&rpar;
						</a>
						<ul class="list-disc pl-8 space-y-1 text-lg">
							<li>
								Tested in the
								<a href="https://cemu.info/" target="_blank" class="italic">
									Cemu
								</a> emulator
							</li>
						</ul>
					</li>
					<li>
						Nintendo 3DS - devkitPro
						<a href="https://github.com/devkitPro/libctru" target="_blank" class="italic">
							&lpar;libctru&rpar;
						</a>,
						<a href="https://github.com/devkitPro/citro3d" target="_blank" class="italic">
							&lpar;citro3d&rpar;
						</a>
						<ul class="list-disc pl-8 space-y-1 text-lg">
							<li>
								Tested on real hardware and in the
								<a href="https://azahar-emu.org/" target="_blank" class="italic">
									Azahar
								</a> emulator
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<div class="space-y-2">
		<h2 class="text-4xl font-bold">
			Architecture
		</h2>
		
		<div class="space-y-1">
			<p class="text-lg">
				Nightbird was originally designed around runtime type reflection and dynamically loaded projects. This approach was great for the editor, but unsuitable for the app especially on the new platform targets. The functionality is planned to be reimplemented for the new editor, while the app will remain statically compiled.
			</p>
			<p class="text-lg">
				Project code containing custom object types was compiled as a shared library and loaded at runtime. These types were then displayed alongside built-in objects in the editor, with custom properties exposed in the inspector and custom behaviour during simulation.
			</p>
		</div>
	</div>
	
	<div class="space-y-2">
		<h2 class="text-4xl font-bold">
			App
		</h2>
		
		<div class="space-y-1">
			<p class="text-lg">
				The app is the executable deployed to the target platform, loading cooked assets generated by the editor.
			</p>
			<p class="text-lg">
				The input provider interface is implemented for all platforms, with audio provider implementations currently in progress.
			</p>
		</div>
	</div>
	
	<div class="space-y-2">
		<h2 class="text-4xl font-bold">
			Editor
		</h2>
		
		<div class="space-y-1">
			<p class="text-lg">
				The Nightbird Editor provides utility functions for importing assets from source formats &lpar;e.g., <span class="italic">.glb</span>, <span class="italic">.flac</span>&rpar; and cooking them into containers &lpar;e.g., .nbtexture, .nbaudio&rpar;. When cooking for the Nintendo 3DS, this uses the platform-specific formats t3x for textures and DSP-ADPCM for audio.
			</p>

			<p class="text-lg">
				The previous version of the editor used
				<a href="https://github.com/ocornut/imgui" class="italic">
					Dear ImGui
				</a>
				for the UI, and this will soon be implemented for the new editor and its new functionality.
			</p>
			
			<div class="space-y-0">
				<p class="text-lg">
					The previous version of the editor features various windows:
				</p>
				<ul class="list-disc pl-8 space-y-1 text-lg">
					<li>Scene Outliner - Displays the objects in the scene in a reparentable hierarchy</li>
					<li>Inspector - Displays serialised properties of the selected object</li>
					<li>Asset Browser - Browse folders and files contained within the Assets folder. Double-click on a scene to open it.</li>
					<li>Scene - Render and traverse the 3D scene from the perspective of the Editor Camera.</li>
				</ul>
				<p class="text-lg">
					When editor UI is reimplemented for the new version of the engine, a Game window is planned where the scene will be rendered from the main camera.
				</p>
			</div>
		</div>
	</div>
</div>